### PR TITLE
Renewed Modern Universal App

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by LyndonArmitage** [comment]
Will try to review all this later today. 

As a note to myself; need to make sure sure to adhere to the [font license](https://tldrlegal.com/license/sil-open-font-license-1.1-%28ofl-1.1%29) for `PressStart2P.ttf` and include copyright notice for the font somewhere if it's used.

**Comment by danimesq** [comment]
Ok, thanks. This is only a draft for now, I'll made more tune ups for the structure in a next pull request. This was my second pull in GitHub. I'm aquired sufficient experience in forks and pull requests now, and I promise work better.

**Comment by danimesq** [comment]
You've forgot? Tomorrow by 9 days haha.
Waiting for response. I need see this being the best pokémon save editor

**Comment by danimesq** [comment]
It is a pleasure and the first time I work on a project of this size. I long to witness the success of this app. I suggest a product name: Poké Universav. I'm with the idea of Universav Initiative. I hope you enjoy and accept my commits. Let's make an awesome app and show the HTML5's / modern platorm's power.

**Comment by danimesq** [comment]
@LyndonArmitage ?

**Comment by danimesq** [comment]
I'm now publishing my fork to gh-pages for you see it live.

**Comment by danimesq** [comment]
Now you can test this pull request/my fork:
http://daniellmesquita.github.io/HTML5PokemonSaveReader/

**Comment by danimesq** [comment]
You can also test it in mobile, but with scroll issues in Firefox.

**Comment by LyndonArmitage** [comment]
Hi Daniell, 

Sorry for not responding at all in the last several months! I have been very busy at work and have not had much time for any projects outside of it. 
The pull request you saw me write was related to something I am working on at work.

Unfortunately as I am very busy and this project was a weekend project that I worked on several years ago. It's probably not something I am going to revisit and contribute much (if any) code to. 

I am glad you've found it interesting and have improved and modified it, and may accept some of the suggestions you have sent me if I ever come back to it. 

I encourage you to continue to improve your branch and treat it as your own project, you can mention in it that the original idea/base parsing code for the save file was created by me. From the looks of it you've done way more than I ever intended to do so I think you should make your name more prominent within the application and take credit.

Thanks and sorry again,

Lyndon Armitage

**Comment by LyndonArmitage** [comment]
From the looks of it my knowledge of managing GitHub projects is kind of bad and I didn't know about the collaborator tab in the project settings. 

I can make you a collaborator on this project if you like, but I think you'd be better off having the project under your own GitHub page.

**Comment by danimesq** [comment]
@LyndonArmitage You can add me as collaborator. I love HTML5 and I enjoy contributing with web apps.

**Comment by danimesq** [comment]
I'll merge this PR, direct pull commits and make an gh-pages branch for it.
Do U have LyndonArmitage.github.io for support it?

**Comment by danimesq** [comment]
Well, thinking better, not have need to make me contributor. I need change name of this app to " Poké Universav". Please disconsidere these comments and PR.

**Comment by danimesq** [comment]
I will keep your creator credits and fork characteristcs of Poké Universav, don't worry. Thanks for creating this and grant permission to fork :wink:

**Comment by danimesq** [comment]
@LyndonArmitage, are you open for a pull request updating the README.md with an link to the up-to-date fork?

**Comment by LyndonArmitage** [comment]
Sure Daniel! Send one over and I will add it to the README!

**Pull request closed without merging**
